import { Navbar } from "./_components/(navbar)";

export const metadata = {
    title: "AttendEase",
    description: "Generated by create next app",
    icons: {
      icon: '/pinsearch.svg', // Path to your custom icon
    },
  };
function PagesLayout({ children }) {
    return(
        <>
            <Navbar />
            <div className="flex h-full pt-20">
                {children}
            </div>
        </>
    );
}

export default PagesLayout;
