import React from 'react';
import { Navbar } from './_components/(navbar)';
import { Sidebar } from './_components/(sidebar)';
import { Container } from './_components/container';

 export const metadata = {
    title: "AttendEase",
    description: "Generated by create next app",
    icons: {
      icon: '/pinsearch.svg', // Path to your custom icon
    },
  };
function Browserlayout({ children }) {
    return (
        <>
            <Navbar />
            <div className="flex h-full pt-20">
                <Sidebar />
                <Container>
                    {children}
                </Container>
            </div>
        </>
    );
}

export default Browserlayout;
