import React from 'react'


export const metadata = {
    title: "AttendEase",
    description: "Generated by create next app",
    icons: {
      icon: '/pinsearch.svg', // Path to your custom icon
    },
  };

function Authlayout({ children }) {
    return (
        <>  {children}</>
    )
}

export default Authlayout